### ISSUE TITLE
Couldn't install with pip

### ISSUE THREAD

**Issue by JulesScholler** [brainglobe/bg-brainrender-gui#12]
When I try to install with pip I get the following:

> (brainGlobe) C:\>pip install bg-brainrender-gui
> ERROR: Could not find a version that satisfies the requirement bg-brainrender-gui (from versions: none)
> ERROR: No matching distribution found for bg-brainrender-gui

**Comment by adamltyson** [comment]
Hi @JulesScholler, are you using Python 3.8? I think there's an issue at the moment that the PyPI trove classifiers say that it's compatible with 3.8, but the setup file says it's not. 3.7 should work.

**Comment by adamltyson** [comment]
@FedeClaudi is it theoretically compatible with 3.8?

**Comment by JulesScholler** [comment]
Will the other brainglobe libraries still work if I downgrade to python 3.7 (brainrender, brainatlas, cellfinder, etc.) ? Or should I create an environment specifically for brainrender-gui?

Thanks for your help

**Comment by adamltyson** [comment]
Everything should work on 3.7 as far as I'm aware, but not necessarily 3.6.

Keeping one environment for analysis (cellfinder, brainreg) and one for visualisation (brainrender) isn't a bad idea though. We don't explicitly test that they work perfectly together (although I use all of them every day).

**Comment by FedeClaudi** [comment]
Hi, 

`brainrender` (and therefore the GUI) could happily work with python 3.8, however `vedo` (which brainrender uses for rendering) may not yet be fully compatible with it (see https://github.com/marcomusy/vedo/issues/236, from python 3.8 only `vtk>=9.0.0 exists). This hasn't been fully tested yet though (at least not by me).

**Comment by JulesScholler** [comment]
Great I will clone the environment and see if there are some incompatibility out of the box and if so work on 2 different envs for analysis and rendering.

Thank you!

**Comment by FedeClaudi** [comment]
Also, please note that I will be releasing [brainrender 2.0](https://github.com/brainglobe/brainrender/pull/125) soon (this week perhaps) and with that the GUI will be moved to be part of brainrender instead of being a standalone package. This repository will be archived accordingly.

**Comment by JulesScholler** [comment]
@FedeClaudi  alright I will wait for it then.

**Comment by FedeClaudi** [comment]
It shouldn't affect compatibility with 3.8 though :)

If you end up testing it I'd be curious to know how it goes!

**Comment by adamltyson** [comment]
> If you end up testing it I'd be curious to know how it goes!

+1 It's great to find out what people are doing with our tools, we normally only hear when things go wrong!

**Comment by JulesScholler** [comment]
As a first step I would like to register and display segmented cell positions in the human brain. Possibly also overlay a low res volumetric intensity image of auto-fluorescence. I don't have nice data for now so it is exploratory but I might contribute in the near future.

**Comment by FedeClaudi** [comment]
Hi @JulesScholler , the GUI is now part of brainrender 2.0.
So you can update brainrender with `pip install brainrender -U` and just use the gui with that, let me know if you bump into any issue.
