### ISSUE TITLE
Improvement suggestion: Option to delete actors from view

### ISSUE THREAD

**Issue by horsto** [brainglobe/bg-brainrender-gui#3]
Since I was using the brainrender GUI quite a bit now, I just wanted to provide a quick suggestion for improvement. When clicking on structures in the structure tree, those structures get added, but they don't seem to be easily removable (you can set the alpha value to 0, but that seems more like a hack). Maybe add a remove button to the list of Actors? 

Also, the relative proportion of the structure tree on the left seems to be fixed / non - resizable. Could you make it so that the user can expand the display area for the structure tree? Digging deeper into the tree means that structures become unreadable unless the GUI is full screen (and cannot be read at all for lower screen resolutions). 

Anyway, thanks a lot for creating this GUI. I cannot wait to see more features added to this in the future.

**Comment by FedeClaudi** [comment]
Hi, 

thanks a lot for the suggestions, great ideas!

You can hide an element from the guy by double clicking on the actor's name in the actors list. This removed the actor from the rendering, but not from the list. I could add a button to remove an actor entirely, the problem is how to use this information to update the structures tree (i.e. to untick the corresponding entry in the tree widget).  I will have to look into this. 

I like the idea of the structure tree's widget being resizible, I will try to add this. 

If you think of any other feature that you'd like to see added let us know. This is still early days for this project so we'd be keen to develop it further based on users feedback.

**Comment by horsto** [comment]
Great, good to hear... 
Thanks for telling me about the double click trick (I then saw that you actually wrote about it in the documentation)! 
 
I understand the problem with updating the structure tree based on actors. 
Maybe they don't have to necessarily interact that much? I for my part would be happy of just having for example a "+" icon next to the structure in the structure viewer which will then momentarily highlight the newly added region in the Actors list (maybe make it blink or so). You could even replicate the "neighbourhood" of the added region in the Actors view (re-create / replicate the tree in some way)? This would also get rid of the problem to keep track of regions that were added but are buried in different sub-trees (you will have to unfold the structure list quite a bit to see them simultaneously). 

For the main canvas it would be great to have little 3D navigational helpers, something like this:
![Screenshot 2020-08-15 at 13 35 41](https://user-images.githubusercontent.com/7548928/90311547-3923e500-defc-11ea-82c5-1b646f3dd227.png)
Or just the option to "reset" or add a specific aspect / view quickly (e.g. if you want to replicate the same view across sessions). And related to that, it would be super cool if you could export what you see in the canvas in some kind of figure-ready format (= user specified resolution / dimensions). 
Cheers!

**Comment by FedeClaudi** [comment]
The small brain in the bottom right corner is intended as a navigation helper like the one you've suggested. it's not interactive however (i.e. you can click on it set the camera angle). I can add buttons or some other widget implement a functionality like the one you've suggested but it won't be part of the main rendering canvas. 
Something similar is already implemented in `brainrender` (the GUI won't replicate all of `brainrender`'s functionality) where you can set the camera the camera position/angle.

Similarly, `brainrender` already lets you take screenshots/videos etc (see [examples](https://docs.brainrender.info/overview/examples)), but I can add a button for screenshots here too.

**Comment by horsto** [comment]
Thanks and sorry for my ignorance. I need to explore the capabilities of `brainrender` more.

**Comment by FedeClaudi** [comment]
no that's fine don't worry! I will be adding some of these things in, they're good ideas. I was just explaining how things are and also letting you know that in the meanwhile you can already have this functionality in brainrender.

**Comment by horsto** [comment]
Great, yes, makes perfect sense!

**Comment by FedeClaudi** [comment]
hey, 

I've implemented some of the features you've suggested. You can try it out with:
```
pip install bg-brainrender-gui==0.0.5rc1
```

----

**changes**:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/17436313/90317720-34265c00-df23-11ea-8a08-6c1eed5b381e.png">

### Screenshots
I've added a button to take screenshots. You can specify where to save the screenshots with
```
brainrender-gui -o path/to/folder
```

### Camera buttons
pretty self explanatory, they reset the camera to one of three default orientations

specifying the screenshots' dimensions and resolutions is not trivial and is not implemented yet in `brainrender` unfortunately. If it's something you'd really need you can open an issue in `brainrender` and I'll see what I can do.

### Adjustable widget widths
It's not reflected in the UI, but you can grab the edges of the side bars to adjust their widths

<img width="700" alt="image" src="https://user-images.githubusercontent.com/17436313/90317764-7d76ab80-df23-11ea-9736-6867dcf1dfd1.png">

<img width="700" alt="image" src="https://user-images.githubusercontent.com/17436313/90317770-85365000-df23-11ea-8ddd-08097828b057.png">

**Comment by horsto** [comment]
Wow, this is very cool! Thanks for doing this! 

I tried out the changes, and it almost all works as described. Here are a few comments: 
- The screenshot function opens a popup stating screenshot saved, and I find it at the right location, but the screenshot file itself is just a transparent background, nothing on it. It doesn't change when I add actors.
- I tried to play with the settings inside the `.brainrender/config.yaml` (hoping to rescue the screenshot behavior) and changed the `DEFAULT_SCREENSHOT_TYPE` to `.jpg`, which then however saves a file as `.jpg.png` instead of just `.jpg` (I assume that's a bug) 
- The camera angle set buttons on the buttons on the bottom work nicely! Would it be possible to include a "three-quarters" or whatever parameter is set as `CAMERA:` default inside the config.yaml? That would be like a reset, or similar. Maybe as double click on the miniature brain? I actually really like that default view. 
- Just thinking out loud, but would it be possible to introduce another default parameter into the config which says "default-orientation" or "mirror-view" (true/false)? Or a button. This would pertain to the fact that the brain for "Side" view and also "three-quarters" shows one side of the brain preferentially. For unilateral experiments it can be quite annoying if always the "wrong" side of the brain is shown. But that's really just me thinking out loud. 
- The resizing of the side panels works nicely! 
- You mentioned in a parallel conversation that you added a default icon to the app. I can't see it in this version (0.0.5rc1). Just wanted to alert in case it should've been included. 

Thanks again, this is all great.

**Comment by FedeClaudi** [comment]
hey, 

* it's true the screenshots are transparent. Not sure what's going on but it seems to be an issue with `vedo`, I've opened [an issue](https://github.com/marcomusy/vedo/issues/195) in vedo, let's see what happens. 

* Yep that's a bug, but the cause is in `vedo`: the screenshot function appends `.png` to the filepath of the screenshot regardless of what was before. For now I will remove this option in `brainrender` as different file formats are not supported by `vedo`.

* I will add a default camera button, that's a good idea. 
* I need to think about what the best way to get a camera like the 'side' one but from the other side

* mmm the icon should be there... do you see any error or warning message?

**Comment by horsto** [comment]
Hi, great, thanks!
No error (your last point / icon):
```
allen mouse atlas (res. 25um)
From: http://www.brain-map.org.com (Wang et al 2020, https://doi.org/10.1016/j.cell.2020.04.007 )
WARNING: Populating font family aliases took 442 ms. Replace uses of missing font family "Roboto" with one that exists to avoid this cost. 
```

**Comment by FedeClaudi** [comment]
I've added a `reset` button that restores the camera to whatever is set as default in `brainrender` and a `side2` button to get the side camera for the other side. You'll need an updated brainrender version for this:
```
pip install brainrender==1.0.0.1rc1                                                                                        
```

to test:
```
pip install bg-brainrender-gui==0.0.5rc2
```

let me know if you see the app icon, it should be there.

**Comment by horsto** [comment]
Thanks, great! New buttons work beautifully. 
The app icon is still absent. 
![Screenshot 2020-08-16 at 14 40 29](https://user-images.githubusercontent.com/7548928/90334533-938d7600-dfce-11ea-8d32-f9361e69aa15.png)

**Comment by FedeClaudi** [comment]
mmm.. weird. I have no idea why it's not showing. At least the rest seems to be working fine. 

Thank you so much for the suggestions, they were great ideas and I feel like the app really improved because them. 
Let me know if you have other ideas!

**Comment by horsto** [comment]
Cool! Yes, I hope to use the app more often in the future (and will provide feedback). Thanks a lot for being so responsive and implementing those features!

**Comment by FedeClaudi** [comment]
@horsto  if you install version `0.0.5rc3` the screenshot should work.
You might have to install `vedo` with `pip install -U git+https://github.com/marcomusy/vedo.git`

**Comment by horsto** [comment]
Thanks, @FedeClaudi ! Works fine on `0.0.5rc3` after updating vedo as you wrote.

**Comment by adamltyson** [comment]
@FedeClaudi, at least for me, the button "side2" doesn't work, and I get:
```
  File "/home/adam/miniconda3/envs/brainreg/lib/python3.7/site-packages/brainrender/Utils/camera.py", line 48, in check_camera_param
    f"Camera name {camera} if not recognized.\nValid cameras: {cameras.keys()}"
ValueError: Camera name sagittal2 if not recognized.
Valid cameras: dict_keys(['sagittal', 'coronal', 'top', 'three_quarters'])
Aborted (core dumped)
```

**Comment by FedeClaudi** [comment]
sorry I haven't published the latest version of brainrender which you need for this because I haven't tested it yet. 
```
pip install brainrender==1.0.0.1rc1                                                                                        
```
should fix it

**Comment by adamltyson** [comment]
Perfect, all fixed. Thanks!
