### ISSUE TITLE
Options to choose object shading

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/bg-brainrender-gui#5]
Hi @FedeClaudi,

Is it possible to choose the shading type for objects when we load them?

Some objects don't look great when loaded using the default (`phong`)
![b](https://user-images.githubusercontent.com/13147259/90907852-73452900-e3cb-11ea-89a7-28da7fba7374.png)

But look much better when you choose `flat`:
![a](https://user-images.githubusercontent.com/13147259/90908125-dd5dce00-e3cb-11ea-8fe6-ad4aa3a57a7f.png):

**Comment by FedeClaudi** [comment]
is that the... **HI**ppocampus? (sorry)

Yeah sure let's add it it. We can have a drop-down menu in the pop-up that already lets you select actor color and alpha when loading stuff.

**Comment by adamltyson** [comment]
I don't know how easy it would be, but do you think it would be possible to click on the actor (after loading) then change the properties?

I'm thinking that users will like to arrange all the different elements of their scene, and **then** play with the visualisation settings.

**Comment by FedeClaudi** [comment]
clicking on the actor in the scene would a bit annoying to code. But if you click on an actor's name on the right, in the bottom right you already have an editor that lets you change color and alpha live. It should be easy to add another option for shader style

**Comment by FedeClaudi** [comment]
might even add a radio button for wireframe

**Comment by adamltyson** [comment]
>  But if you click on an actor's name on the right, in the bottom right you already have an editor that lets you change color and alpha live.

Missed that, that's perfect

**Comment by FedeClaudi** [comment]
do you want to include it in your PR or do you want me to do it?

**Comment by adamltyson** [comment]
I can look into this, but I'll probably do it separately from my PR (I need to think properly about what's the most general way to save & load a 1D structure).
